### ISSUE TITLE
Move pyaccel.graphics to apsuite?

### ISSUE THREAD

**Issue by afonsoharuo** [lnls-fac/apsuite#1]

**Comment by fernandohds564** [comment]
I think it is well placed in pyaccel. I think the visualization of the lattice and the twiss parameters is a basic functionality and fits in the philosophy of development of pyaccel which is to build a compact and generic accelerator tool.

**Comment by xresende** [comment]
I think of pyaccel as a non-interactive library. In that sense graphic
functionalities should be more appropriately located in apsuite. That's my
vote. But I dont see any problem in giving up the non-interactive character
of pyaccel.

**Comment by afonsoharuo** [comment]
Will leave it as is.
